### ISSUE TITLE
Option to disable log prefixing

### ISSUE THREAD

**Issue by guybedford** [fastly/js-compute-runtime#1063]
Currently all log messages are prefixed with `Log: ` - it could be worth providing an option to disable this prefixing.

**Comment by jsocol** [comment]
I have an app using `js-compute-runtime` that's trying to output JSON-formatted logs, and parsing is broken by these prefixes. In some cases there are other places to handle it, but since this is atypical behavior for `console`, it'd be great to be able to switch it to behave as it would in Node or tests

**Comment by guybedford** [comment]
Added in https://github.com/fastly/js-compute-runtime/pull/1065.
