### ISSUE TITLE
Missing SharedArrayBuffer implementation

### ISSUE THREAD

**Issue by JakeChampion** [fastly/js-compute-runtime#32]
When building a project which makes use of `SharedArrayBuffer`, this error is thrown:
>Exception while evaluating JS: (new ReferenceError("SharedArrayBuffer is not defined", "<stdin>", 622))

I've worked around the issue in my project with a very hacky patch (`globalThis.SharedArrayBuffer = ArrayBuffer;`)

I think we should add a `SharedArrayBuffer` implementation as it is used within some packages such as the `data-urls` package which is used in reference/example code on the Fastly Docs website -- https://developer.fastly.com/learning/compute/migrate/#build-an-image-response

**Comment by tschneidereit** [comment]
This one's a bit tricky: we don't have a way to actually implement `SharedArrayBuffer`, and pretending that we support it while we don't means that any code that feature-detects them to actually use them would end up doing the wrong thing.

The issue you mention is due to the webidl-conversions library [assuming SAB support](https://github.com/jsdom/webidl-conversions/issues/31#issuecomment-629668652). While that'd be trivial to fix in webidl-conversions, they made clear that they're not interested, as per the comment I linked.

(One way to fix it would be to change the relevant lines to something like
```js
const sabByteLengthGetter =
    typeof SharedArrayBuffer == "undefined" ? null : Object.getOwnPropertyDescriptor(SharedArrayBuffer.prototype, "byteLength").get;
```

That'd cause `isSharedArrayBuffer` to always return false, because trying to call a `null` value throws.)

**Comment by guybedford** [comment]
Moving to https://github.com/bytecodealliance/StarlingMonkey/issues/115.
