### ISSUE TITLE
Add support for Apple Silicon 

### ISSUE THREAD

**Issue by phamann** [fastly/js-compute-runtime#76]
We currently don't produce a target binary for apple silicon (i.e. arm64). 

This should hopefully be a simple addition to the [CI pipline](https://github.com/fastly/js-compute-runtime/blob/main/.github/workflows/main.yml#L165-L175) matrix. However the current worflow in the CI pipeline makes certain assumptions that `macOS` is a single architecture, and therefore may need somne light refactoring.

**Comment by zakariamofaddel** [comment]
Hey Patrick😁 
I've had issues with the `@fastly/js-compute` npm package, where there is a `js-compute-runtime-cli.js` file that checks the current platform the CLI is running on.
When running the cli commands on an M1 system everything works great, because you can see the Darwin version is included in this map in that file:
```javascript
...

function getPlatform() {
  const osMap = {
    Windows_NT: {
      name: "windows",
      archs: {
        x64: "x86_64",
      },
    },
    Linux: {
      name: "linux",
      archs: {
        x64: "x86_64",
      },
    },
    Darwin: {
      name: "macos",
      archs: {
        arm64: "x86_64",
        x64: "x86_64",
      },
    },
  };
...
```

But when installing the cli on a debian based container running on the same M1 machine, I face an error, because `osMap.Linux.archs` is missing `arm64`

Is there a solution for that or is there anything planned for it?

**Comment by JakeChampion** [comment]
This was resolved when we rewrote the rust cli to JavaScript in version v0.5.7 🥳
