### ISSUE TITLE
Implement hostcall for obtaining server IP

### ISSUE THREAD

**Issue by kphillips** [fastly/js-compute-runtime#853]
A hostcall to expose the IP address on which the server received the HTTP request was recently added. Support has already been added in the Rust SDK (see https://docs.rs/fastly/latest/fastly/handle/fn.server_ip_addr.html), and needs to be added to the JS SDK.

**Comment by guybedford** [comment]
Hi @kphillips. Thanks for checking this one. Support for this was added in 3.18.0, see https://js-compute-reference-docs.edgecompute.app/docs/globals/Response/prototype/ip. Feedback very welcome!

**Comment by kphillips** [comment]
Hi @guybedford. The Rust docs characterize this as "the IP address on which the server _received_ the HTTP request," but this function appears to relate to an IP address where the backend response was received, because it explains an `undefined` case where there was no backend response, either from a cached or a synthetic response. I don't know whether those would always be the same address, and I don't think it's possible for the _receiving_ side to have an `undefined` case at this time.

**Comment by guybedford** [comment]
Ahh right, so we implement the client IP and the request IP for fetch requests, but there's also a server IP.

Certainly we can add this.

It doesn't feel like it belongs on `clientInfo` on the fetch event since it is server metadata. Possible implementations might include:

* A function under `fastly:experimental`
* `fetchEvent.ip`
* `get Request.prototype.ip`

Marking as a feature, we'll add this as soon as we can.
