### ISSUE TITLE
Inconsistencies between Local & Deployment Versions

### ISSUE THREAD

**Issue by Abiti-936** [fastly/js-compute-runtime#88]
When I develop My GraphQL API with Fastly CLI in My Local Machine everything was working fine but, after a Deployment Unexpected Error will Pop Like Service Unavailable Error. Please Fix these Inconsistencies as they are bad for anyone who don't see Error in Development & then the App Crashes after Production Deployment.

You can use My GraphQL Yoga Project as an Example in here:
https://github.com/Abiti-936/graphql-yoga-compute-edge
https://gql-yoga.edgecompute.app

**Comment by JakeChampion** [comment]
Hi @Abiti-936 - this repo is intended primarily as a development workspace for the Compute@Edge engineers who work on the JavaScript Runtime, and others who would like to contribute to its development.

As your request is to review a C@E service and it's corresponding code, I would suggest using Fastly's support process, e.g. by emailing [support@fastly.com](mailto:support@fastly.com), where support staff can provide support and answer any questions you may have.

Thank you.

P.S. 
My assumption on the cause of this issue is that `@graphql-yoga/common` does not yet support Fastly C@E - I would recommend contacting the people who work on that project and see if they have plans to support Fastly C@E.
